services:
  db_dev:
    container_name: app_db_development
    image: postgres:16-alpine
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "7Z7(9f<3ti?a>p>w(t078^NAVAW{,£N,fp%[u(V&0x7n^n"
      POSTGRES_DB: db_app
    volumes: # (bind mount & volume)
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/script:/docker-entrypoint-initdb.d/
      - ./postgres/logs:/mnt/log
      - app_db_dev:/var/lib/postgresql/data
    networks:
      - app_network
volumes:
  app_db_dev:
networks:
  app_network:
    driver: bridge
