### Get all users
GET http://localhost:3000/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJjaHJpc3RpYW4iLCJpYXQiOjE3MTg0NzE1MzAsImV4cCI6MTcxODQ3NTEzMH0.eVYDlsLHowo8qgbH1DZ8Ngixv7xJ_ARshKFkTNSNXo8

### Get specific user (exists)
GET http://localhost:3000/user?id=2 HTTP/1.1

### Get specific user (does not exist)
GET http://localhost:3000/user?id=999 HTTP/1.1

### Create user
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "username": "christian",
    "password": "123",
    "role": 1
}

### Update user
PATCH http://localhost:3000/user?id=5 HTTP/1.1
Content-Type: application/json

{
    "password": "password123JKHKHK"
}

### Delete user
DELETE http://localhost:3000/user?id=5 HTTP/1.1

// -----------------------
// #### Relation ROLE ####
// -----------------------

### Get all roles
GET http://localhost:3000/user/2/role HTTP/1.1